change parameters yaml key to params
config validator started complaining and build error appearing seemingly randomly

$ circleci config validate
Error: ERROR IN CONFIG FILE:
[#/parameters/sector_builder_tests_param] 3 schema violations found
1. [#/parameters/sector_builder_tests_param] required key [default] not found
2. [#/parameters/sector_builder_tests_param] required key [type] not found
3. [#/parameters/sector_builder_tests_param] extraneous key [sector_builder_tests] is not permitted

s/parameters/params/ fixes error so assuming parameters has become a reserved top level key